name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, pdo_mysql

      - name: Install dependencies
        run: composer install --no-progress

      - name: Build
        run: npm install && npm run build

      - name: Deploy to Vercel
        uses: vercel/deploy-action@v1
        with:
          vercel-project: prueba-tecnica-casino-front
